[env:esp32-3248S035R]
platform = espressif32
board = esp32-3248S035R
framework = arduino
monitor_speed = 115200
build_flags = 
	-D ST7796_DRIVER
	-D TFT_WIDTH=480
	-D TFT_HEIGHT=320
	-D TFT_CS=5
	-D TFT_DC=4
	-D TFT_RST=16
	-D TOUCH_CS=33
	-D BACKLIGHT_PIN=27
	-D FLOCK_REAPER=1
lib_deps = 
	TFT_eSPI
	XPT2046_Touchscreen
	lvgl
	justcallmekoko/ESP32Marauder
